files:
  - source: /udata_tabular_preview/translations/*.pot
    translation: /udata_tabular_preview/translations/%two_letters_code%/LC_MESSAGES/udata.po
  - source: /udata-tabular-preview/locales/en.json
    translation: /udata-tabular-preview/locales/%two_letters_code%.json
